"use client";

import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";
import { FormEvent, useState } from "react";

const starters = ["Explain how to investigate a slow API route.", "Draft a plan to add authentication.", "What should I check before a production deployment?"];

export function AssistantChat() {
  const [input, setInput] = useState("");
  const { messages, sendMessage, status, error } = useChat({ transport: new DefaultChatTransport({ api: "/api/chat" }) });
  const isLoading = status === "submitted" || status === "streaming";
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const text = input.trim(); if (!text || isLoading) return; sendMessage({ text }); setInput(""); };
  return <section className="mx-auto flex w-full max-w-4xl flex-1 flex-col px-4 py-8 sm:px-6"><div className="border-b border-border pb-6"><p className="label-mono">RoxAI assistant</p><h1 className="mt-3 text-2xl font-medium tracking-tight">Ask about an engineering task.</h1><p className="mt-2 text-sm text-muted-foreground">Responses stream from the configured model through Vercel AI Gateway.</p></div><div className="flex flex-1 flex-col gap-5 py-8">{messages.length === 0 ? <div className="my-auto"><p className="text-lg text-foreground">What are you working on?</p><div className="mt-5 flex flex-wrap gap-2">{starters.map((starter) => <button key={starter} onClick={() => setInput(starter)} className="rounded-md border border-border bg-surface px-3 py-2 text-left text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-foreground">{starter}</button>)}</div></div> : messages.map((message) => <article key={message.id} className={`max-w-3xl border-l-2 pl-4 ${message.role === "user" ? "border-muted-foreground" : "border-primary"}`}><p className="label-mono mb-2">{message.role === "user" ? "You" : "RoxAI"}</p><div className="whitespace-pre-wrap text-sm leading-7 text-foreground">{message.parts.map((part, index) => part.type === "text" ? <span key={index}>{part.text}</span> : null)}</div></article>)}{isLoading ? <p className="label-mono animate-pulse text-primary">RoxAI is thinking</p> : null}{error ? <p role="alert" className="rounded-md border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive">{error.message || "The assistant request failed. Verify AI_GATEWAY_API_KEY and try again."}</p> : null}</div><form onSubmit={submit} className="sticky bottom-4 border border-border bg-surface p-3 shadow-xl shadow-black/20"><label htmlFor="message" className="sr-only">Message RoxAI</label><textarea id="message" value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} placeholder="Ask RoxAI about your software…" rows={3} className="w-full resize-none bg-transparent p-2 text-sm outline-none placeholder:text-muted-foreground"/><div className="flex items-center justify-between border-t border-border pt-3"><span className="text-xs text-muted-foreground">Enter to send · Shift+Enter for newline</span><button type="submit" disabled={!input.trim() || isLoading} className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50">Send</button></div></form></section>;
}
