import Link from "next/link";

const plans = [
  { name: "Starter", price: "$0", description: "For evaluating RoxAI with a focused engineering workflow.", features: ["Streaming assistant", "Session-based conversations", "Bring your AI Gateway key"] },
  { name: "Team", price: "$20", description: "For teams that want a shared workspace and production workflows.", features: ["Everything in Starter", "Shared project context", "Review-ready change drafts"], highlighted: true },
];

export default function PricingPage() {
  return <section className="mx-auto w-full max-w-6xl px-4 py-20 sm:px-6"><p className="label-mono">Simple by design</p><h1 className="mt-5 max-w-2xl text-4xl font-medium tracking-[-0.04em] sm:text-5xl">Start with the assistant. Scale with your engineering team.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">RoxAI is ready to run against Vercel AI Gateway. Your AI provider usage remains under your control.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{plans.map((plan) => <article key={plan.name} className={`border p-7 ${plan.highlighted ? "border-primary bg-surface" : "border-border bg-surface/50"}`}><div className="flex items-start justify-between"><div><h2 className="text-xl font-medium">{plan.name}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{plan.description}</p></div>{plan.highlighted ? <span className="label-mono text-primary">Recommended</span> : null}</div><p className="mt-8 text-4xl font-medium">{plan.price}<span className="ml-1 text-sm font-normal text-muted-foreground">/ month</span></p><ul className="mt-8 space-y-3 text-sm text-muted-foreground">{plan.features.map((feature) => <li key={feature} className="flex gap-3"><span className="text-primary">+</span>{feature}</li>)}</ul><Link href="/chat" className={`mt-9 inline-flex rounded-md px-4 py-2.5 text-sm font-medium ${plan.highlighted ? "bg-primary text-primary-foreground" : "border border-border text-foreground"}`}>Try RoxAI</Link></article>)}</div><p className="mt-8 text-sm text-muted-foreground">This MVP does not process payments or manage accounts. Pricing is a product outline until those flows are connected.</p></section>;
}
